-- Librélula · Clubes de lectura V1
-- Ejecutar una sola vez en Supabase SQL Editor.
-- No borra libros, perfiles, bibliotecas, reseñas ni actividad existente.

create extension if not exists pgcrypto;

create table if not exists public.reading_clubs (
  id bigint generated by default as identity primary key,
  owner_id uuid not null references public.profiles(id) on delete cascade,
  name text not null check (char_length(trim(name)) between 3 and 80),
  description text not null default '',
  visibility text not null default 'public' check (visibility in ('public', 'private')),
  current_book_id text references public.books(id) on delete set null,
  banner_url text not null default '',
  icon_url text not null default '',
  accent_color text not null default '#8f4b2f',
  invite_code text not null unique default upper(substr(replace(gen_random_uuid()::text, '-', ''), 1, 10)),
  next_meeting_at timestamptz,
  meeting_label text not null default 'Reunión del club',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.reading_club_members (
  id bigint generated by default as identity primary key,
  club_id bigint not null references public.reading_clubs(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  role text not null default 'member' check (role in ('owner', 'moderator', 'member')),
  status text not null default 'active' check (status in ('active', 'invited', 'pending')),
  current_chapter integer not null default 1 check (current_chapter >= 1),
  progress integer not null default 0 check (progress between 0 and 100),
  joined_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (club_id, user_id)
);

create table if not exists public.reading_club_chapters (
  id bigint generated by default as identity primary key,
  club_id bigint not null references public.reading_clubs(id) on delete cascade,
  chapter_number integer not null check (chapter_number >= 1),
  title text not null default '',
  created_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  unique (club_id, chapter_number)
);

create table if not exists public.reading_club_posts (
  id bigint generated by default as identity primary key,
  club_id bigint not null references public.reading_clubs(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  channel text not null default 'general' check (channel in ('general', 'chapter')),
  chapter_number integer,
  content text not null default '',
  quote_text text not null default '',
  image_path text not null default '',
  contains_spoilers boolean not null default false,
  parent_post_id bigint references public.reading_club_posts(id) on delete cascade,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (
    (channel = 'general' and chapter_number is null)
    or (channel = 'chapter' and chapter_number is not null and chapter_number >= 1)
  ),
  check (char_length(trim(content)) > 0 or quote_text <> '' or image_path <> '')
);

create table if not exists public.reading_club_post_reactions (
  post_id bigint not null references public.reading_club_posts(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  reaction text not null default 'heart' check (reaction in ('heart', 'leaf')),
  created_at timestamptz not null default now(),
  primary key (post_id, user_id, reaction)
);

create table if not exists public.reading_club_meetings (
  id bigint generated by default as identity primary key,
  club_id bigint not null references public.reading_clubs(id) on delete cascade,
  title text not null default 'Reunión del club',
  starts_at timestamptz not null,
  location text not null default '',
  description text not null default '',
  created_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now()
);

create index if not exists reading_clubs_visibility_idx
  on public.reading_clubs (visibility, created_at desc);
create index if not exists reading_club_members_user_idx
  on public.reading_club_members (user_id, status, joined_at desc);
create index if not exists reading_club_members_club_idx
  on public.reading_club_members (club_id, status);
create index if not exists reading_club_posts_feed_idx
  on public.reading_club_posts (club_id, channel, chapter_number, created_at desc);
create index if not exists reading_club_meetings_club_idx
  on public.reading_club_meetings (club_id, starts_at);

create or replace function public.reading_club_touch_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists reading_clubs_touch_updated_at on public.reading_clubs;
create trigger reading_clubs_touch_updated_at
before update on public.reading_clubs
for each row execute function public.reading_club_touch_updated_at();

drop trigger if exists reading_club_members_touch_updated_at on public.reading_club_members;
create trigger reading_club_members_touch_updated_at
before update on public.reading_club_members
for each row execute function public.reading_club_touch_updated_at();

drop trigger if exists reading_club_posts_touch_updated_at on public.reading_club_posts;
create trigger reading_club_posts_touch_updated_at
before update on public.reading_club_posts
for each row execute function public.reading_club_touch_updated_at();

create or replace function public.reading_club_add_owner()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.reading_club_members (club_id, user_id, role, status, current_chapter, progress)
  values (new.id, new.owner_id, 'owner', 'active', 1, 0)
  on conflict (club_id, user_id) do update
    set role = 'owner', status = 'active';
  return new;
end;
$$;

drop trigger if exists reading_club_add_owner_after_insert on public.reading_clubs;
create trigger reading_club_add_owner_after_insert
after insert on public.reading_clubs
for each row execute function public.reading_club_add_owner();

create or replace function public.is_reading_club_member(
  p_club_id bigint,
  p_user_id uuid default auth.uid()
)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.reading_club_members m
    where m.club_id = p_club_id
      and m.user_id = p_user_id
      and m.status = 'active'
  );
$$;

create or replace function public.is_reading_club_admin(
  p_club_id bigint,
  p_user_id uuid default auth.uid()
)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.reading_club_members m
    where m.club_id = p_club_id
      and m.user_id = p_user_id
      and m.status = 'active'
      and m.role in ('owner', 'moderator')
  );
$$;

create or replace function public.join_reading_club(
  p_club_id bigint,
  p_invite_code text default null
)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  v_club public.reading_clubs%rowtype;
begin
  if auth.uid() is null then
    raise exception 'Debes iniciar sesión para unirte a un club.';
  end if;

  select * into v_club
  from public.reading_clubs
  where id = p_club_id;

  if not found then
    raise exception 'El club no existe.';
  end if;

  if v_club.visibility = 'private'
     and upper(trim(coalesce(p_invite_code, ''))) <> upper(v_club.invite_code) then
    raise exception 'El código de invitación no es válido.';
  end if;

  insert into public.reading_club_members (club_id, user_id, role, status)
  values (p_club_id, auth.uid(), 'member', 'active')
  on conflict (club_id, user_id) do update
    set status = 'active', updated_at = now();

  return true;
end;
$$;

create or replace function public.join_reading_club_by_code(p_invite_code text)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  v_club_id bigint;
begin
  if auth.uid() is null then
    raise exception 'Debes iniciar sesión para usar una invitación.';
  end if;

  select id into v_club_id
  from public.reading_clubs
  where visibility = 'private'
    and upper(invite_code) = upper(trim(coalesce(p_invite_code, '')))
  limit 1;

  if v_club_id is null then
    raise exception 'El código de invitación no es válido.';
  end if;

  insert into public.reading_club_members (club_id, user_id, role, status)
  values (v_club_id, auth.uid(), 'member', 'active')
  on conflict (club_id, user_id) do update
    set status = 'active', updated_at = now();

  return v_club_id;
end;
$$;

create or replace function public.leave_reading_club(p_club_id bigint)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  v_role text;
begin
  if auth.uid() is null then
    raise exception 'Debes iniciar sesión.';
  end if;

  select role into v_role
  from public.reading_club_members
  where club_id = p_club_id and user_id = auth.uid();

  if v_role = 'owner' then
    raise exception 'La persona creadora no puede abandonar el club sin transferirlo.';
  end if;

  delete from public.reading_club_members
  where club_id = p_club_id and user_id = auth.uid();

  return true;
end;
$$;

create or replace function public.update_reading_club_progress(
  p_club_id bigint,
  p_current_chapter integer,
  p_progress integer
)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
begin
  if auth.uid() is null then
    raise exception 'Debes iniciar sesión.';
  end if;

  update public.reading_club_members
  set current_chapter = greatest(1, coalesce(p_current_chapter, 1)),
      progress = greatest(0, least(100, coalesce(p_progress, 0))),
      updated_at = now()
  where club_id = p_club_id
    and user_id = auth.uid()
    and status = 'active';

  if not found then
    raise exception 'No perteneces a este club.';
  end if;

  return true;
end;
$$;

grant execute on function public.join_reading_club(bigint, text) to authenticated;
grant execute on function public.join_reading_club_by_code(text) to authenticated;
grant execute on function public.leave_reading_club(bigint) to authenticated;
grant execute on function public.update_reading_club_progress(bigint, integer, integer) to authenticated;
revoke execute on function public.is_reading_club_member(bigint, uuid) from public;
grant execute on function public.is_reading_club_member(bigint, uuid) to anon, authenticated;
revoke execute on function public.is_reading_club_admin(bigint, uuid) from public, anon;
grant execute on function public.is_reading_club_admin(bigint, uuid) to authenticated;

alter table public.reading_clubs enable row level security;
alter table public.reading_club_members enable row level security;
alter table public.reading_club_chapters enable row level security;
alter table public.reading_club_posts enable row level security;
alter table public.reading_club_post_reactions enable row level security;
alter table public.reading_club_meetings enable row level security;

-- Clubes: visibles si son públicos o perteneces a ellos.
drop policy if exists reading_clubs_select on public.reading_clubs;
create policy reading_clubs_select
on public.reading_clubs for select
to anon, authenticated
using (
  visibility = 'public'
  or public.is_reading_club_member(id, auth.uid())
  or owner_id = auth.uid()
);

drop policy if exists reading_clubs_insert on public.reading_clubs;
create policy reading_clubs_insert
on public.reading_clubs for insert
to authenticated
with check (owner_id = auth.uid());

drop policy if exists reading_clubs_update on public.reading_clubs;
create policy reading_clubs_update
on public.reading_clubs for update
to authenticated
using (public.is_reading_club_admin(id, auth.uid()))
with check (public.is_reading_club_admin(id, auth.uid()));

drop policy if exists reading_clubs_delete on public.reading_clubs;
create policy reading_clubs_delete
on public.reading_clubs for delete
to authenticated
using (owner_id = auth.uid());

-- Miembros.
drop policy if exists reading_club_members_select on public.reading_club_members;
create policy reading_club_members_select
on public.reading_club_members for select
to authenticated
using (
  public.is_reading_club_member(club_id, auth.uid())
  or exists (
    select 1 from public.reading_clubs c
    where c.id = club_id and c.visibility = 'public'
  )
);

drop policy if exists reading_club_members_update on public.reading_club_members;
create policy reading_club_members_update
on public.reading_club_members for update
to authenticated
using (user_id = auth.uid() or public.is_reading_club_admin(club_id, auth.uid()))
with check (user_id = auth.uid() or public.is_reading_club_admin(club_id, auth.uid()));

drop policy if exists reading_club_members_delete on public.reading_club_members;
create policy reading_club_members_delete
on public.reading_club_members for delete
to authenticated
using (user_id = auth.uid() or public.is_reading_club_admin(club_id, auth.uid()));

-- Capítulos.
drop policy if exists reading_club_chapters_select on public.reading_club_chapters;
create policy reading_club_chapters_select
on public.reading_club_chapters for select
to authenticated
using (public.is_reading_club_member(club_id, auth.uid()));

drop policy if exists reading_club_chapters_manage on public.reading_club_chapters;
create policy reading_club_chapters_manage
on public.reading_club_chapters for all
to authenticated
using (public.is_reading_club_admin(club_id, auth.uid()))
with check (public.is_reading_club_admin(club_id, auth.uid()));

-- Publicaciones.
drop policy if exists reading_club_posts_select on public.reading_club_posts;
create policy reading_club_posts_select
on public.reading_club_posts for select
to authenticated
using (public.is_reading_club_member(club_id, auth.uid()));

drop policy if exists reading_club_posts_insert on public.reading_club_posts;
create policy reading_club_posts_insert
on public.reading_club_posts for insert
to authenticated
with check (
  user_id = auth.uid()
  and public.is_reading_club_member(club_id, auth.uid())
);

drop policy if exists reading_club_posts_update on public.reading_club_posts;
create policy reading_club_posts_update
on public.reading_club_posts for update
to authenticated
using (user_id = auth.uid() or public.is_reading_club_admin(club_id, auth.uid()))
with check (user_id = auth.uid() or public.is_reading_club_admin(club_id, auth.uid()));

drop policy if exists reading_club_posts_delete on public.reading_club_posts;
create policy reading_club_posts_delete
on public.reading_club_posts for delete
to authenticated
using (user_id = auth.uid() or public.is_reading_club_admin(club_id, auth.uid()));

-- Reacciones.
drop policy if exists reading_club_reactions_select on public.reading_club_post_reactions;
create policy reading_club_reactions_select
on public.reading_club_post_reactions for select
to authenticated
using (
  exists (
    select 1 from public.reading_club_posts p
    where p.id = post_id
      and public.is_reading_club_member(p.club_id, auth.uid())
  )
);

drop policy if exists reading_club_reactions_insert on public.reading_club_post_reactions;
create policy reading_club_reactions_insert
on public.reading_club_post_reactions for insert
to authenticated
with check (
  user_id = auth.uid()
  and exists (
    select 1 from public.reading_club_posts p
    where p.id = post_id
      and public.is_reading_club_member(p.club_id, auth.uid())
  )
);

drop policy if exists reading_club_reactions_delete on public.reading_club_post_reactions;
create policy reading_club_reactions_delete
on public.reading_club_post_reactions for delete
to authenticated
using (user_id = auth.uid());

-- Reuniones.
drop policy if exists reading_club_meetings_select on public.reading_club_meetings;
create policy reading_club_meetings_select
on public.reading_club_meetings for select
to authenticated
using (public.is_reading_club_member(club_id, auth.uid()));

drop policy if exists reading_club_meetings_manage on public.reading_club_meetings;
create policy reading_club_meetings_manage
on public.reading_club_meetings for all
to authenticated
using (public.is_reading_club_admin(club_id, auth.uid()))
with check (public.is_reading_club_admin(club_id, auth.uid()));

-- Imágenes de publicaciones del club.
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'club-media',
  'club-media',
  true,
  5242880,
  array['image/jpeg', 'image/png', 'image/webp', 'image/gif']
)
on conflict (id) do update
set public = excluded.public,
    file_size_limit = excluded.file_size_limit,
    allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists club_media_select on storage.objects;
create policy club_media_select
on storage.objects for select
to anon, authenticated
using (bucket_id = 'club-media');

drop policy if exists club_media_insert on storage.objects;
create policy club_media_insert
on storage.objects for insert
to authenticated
with check (
  bucket_id = 'club-media'
  and (storage.foldername(name))[1] = auth.uid()::text
);

drop policy if exists club_media_update on storage.objects;
create policy club_media_update
on storage.objects for update
to authenticated
using (
  bucket_id = 'club-media'
  and (storage.foldername(name))[1] = auth.uid()::text
)
with check (
  bucket_id = 'club-media'
  and (storage.foldername(name))[1] = auth.uid()::text
);

drop policy if exists club_media_delete on storage.objects;
create policy club_media_delete
on storage.objects for delete
to authenticated
using (
  bucket_id = 'club-media'
  and (storage.foldername(name))[1] = auth.uid()::text
);

grant select on public.reading_clubs to anon, authenticated;
grant insert, update, delete on public.reading_clubs to authenticated;
grant select, update, delete on public.reading_club_members to authenticated;
grant select, insert, update, delete on public.reading_club_chapters to authenticated;
grant select, insert, update, delete on public.reading_club_posts to authenticated;
grant select, insert, delete on public.reading_club_post_reactions to authenticated;
grant select, insert, update, delete on public.reading_club_meetings to authenticated;
grant usage, select on sequence public.reading_clubs_id_seq to authenticated;
grant usage, select on sequence public.reading_club_members_id_seq to authenticated;
grant usage, select on sequence public.reading_club_chapters_id_seq to authenticated;
grant usage, select on sequence public.reading_club_posts_id_seq to authenticated;
grant usage, select on sequence public.reading_club_meetings_id_seq to authenticated;

select
  to_regclass('public.reading_clubs') is not null as clubes,
  to_regclass('public.reading_club_members') is not null as miembros,
  to_regclass('public.reading_club_posts') is not null as conversaciones,
  to_regclass('public.reading_club_chapters') is not null as capitulos,
  exists(select 1 from storage.buckets where id = 'club-media') as imagenes_club;
