+-- Amplía las colecciones editoriales con 15 títulos reales por temática.
-- Los libros se identifican por título y autor antes de enlazarlos, para no duplicar fichas existentes.
insert into public.books (id,title,author,genre,year,language,cover,provider,source_id)
select v.id,v.title,v.author,v.genre,v.year,v.language,v.cover,v.provider,v.source_id
from (values
('curated_the_secret_history','The Secret History','Donna Tartt','["Narrativa contemporánea"]','1992','en','https://covers.openlibrary.org/b/title/The%20Secret%20History-M.jpg','open_library','curated_the_secret_history'),
('curated_if_we_were_villains','If We Were Villains','M. L. Rio','["Narrativa contemporánea"]','2017','en','https://covers.openlibrary.org/b/title/If%20We%20Were%20Villains-M.jpg','open_library','curated_if_we_were_villains'),
('curated_babel','Babel','R. F. Kuang','["Narrativa contemporánea"]','2022','en','https://covers.openlibrary.org/b/title/Babel-M.jpg','open_library','curated_babel'),
('curated_the_maidens','The Maidens','Alex Michaelides','["Narrativa contemporánea"]','2021','en','https://covers.openlibrary.org/b/title/The%20Maidens-M.jpg','open_library','curated_the_maidens'),
('curated_the_likeness','The Likeness','Tana French','["Narrativa contemporánea"]','2008','en','https://covers.openlibrary.org/b/title/The%20Likeness-M.jpg','open_library','curated_the_likeness'),
('curated_the_goldfinch','The Goldfinch','Donna Tartt','["Narrativa contemporánea"]','2013','en','https://covers.openlibrary.org/b/title/The%20Goldfinch-M.jpg','open_library','curated_the_goldfinch'),
('curated_dead_poets_society','Dead Poets Society','N. H. Kleinbaum','["Narrativa contemporánea"]','1988','en','https://covers.openlibrary.org/b/title/Dead%20Poets%20Society-M.jpg','open_library','curated_dead_poets_society'),
('curated_vita_nostra','Vita Nostra','Marina Dyachenko','["Narrativa contemporánea"]','2007','en','https://covers.openlibrary.org/b/title/Vita%20Nostra-M.jpg','open_library','curated_vita_nostra'),
('curated_ace_of_spades','Ace of Spades','Faridah Àbíké-Íyímídé','["Narrativa contemporánea"]','2021','en','https://covers.openlibrary.org/b/title/Ace%20of%20Spades-M.jpg','open_library','curated_ace_of_spades'),
('curated_catherine_house','Catherine House','Elisabeth Thomas','["Narrativa contemporánea"]','2020','en','https://covers.openlibrary.org/b/title/Catherine%20House-M.jpg','open_library','curated_catherine_house'),
('curated_the_secret_place','The Secret Place','Tana French','["Narrativa contemporánea"]','2014','en','https://covers.openlibrary.org/b/title/The%20Secret%20Place-M.jpg','open_library','curated_the_secret_place'),
('curated_the_lake_of_dead_languages','The Lake of Dead Languages','Carol Goodman','["Narrativa contemporánea"]','2002','en','https://covers.openlibrary.org/b/title/The%20Lake%20of%20Dead%20Languages-M.jpg','open_library','curated_the_lake_of_dead_languages'),
('curated_the_cloisters','The Cloisters','Katy Hays','["Narrativa contemporánea"]','2023','en','https://covers.openlibrary.org/b/title/The%20Cloisters-M.jpg','open_library','curated_the_cloisters'),
('curated_an_education_in_malice','An Education in Malice','Mira Grant','["Narrativa contemporánea"]','2024','en','https://covers.openlibrary.org/b/title/An%20Education%20in%20Malice-M.jpg','open_library','curated_an_education_in_malice'),
('curated_the_atlas_six','The Atlas Six','Olivie Blake','["Narrativa contemporánea"]','2022','en','https://covers.openlibrary.org/b/title/The%20Atlas%20Six-M.jpg','open_library','curated_the_atlas_six'),
('curated_la_mala_costumbre','La mala costumbre','Alana S. Portero','["Narrativa contemporánea"]','2023','es','https://covers.openlibrary.org/b/title/La%20mala%20costumbre-M.jpg','open_library','curated_la_mala_costumbre'),
('curated_call_me_by_your_name','Call Me by Your Name','André Aciman','["Narrativa contemporánea"]','2007','es','https://covers.openlibrary.org/b/title/Call%20Me%20by%20Your%20Name-M.jpg','open_library','curated_call_me_by_your_name'),
('curated_aristotle_and_dante_discover_the_secrets_of_the_universe','Aristotle and Dante Discover the Secrets of the Universe','Benjamin Alire Sáenz','["Narrativa contemporánea"]','2012','es','https://covers.openlibrary.org/b/title/Aristotle%20and%20Dante%20Discover%20the%20Secrets%20of%20the%20Universe-M.jpg','open_library','curated_aristotle_and_dante_discover_the_secrets_of_the_universe'),
('curated_the_song_of_achilles','The Song of Achilles','Madeline Miller','["Narrativa contemporánea"]','2011','es','https://covers.openlibrary.org/b/title/The%20Song%20of%20Achilles-M.jpg','open_library','curated_the_song_of_achilles'),
('curated_red_white_royal_blue','Red, White & Royal Blue','Casey McQuiston','["Narrativa contemporánea"]','2019','es','https://covers.openlibrary.org/b/title/Red%2C%20White%20%26%20Royal%20Blue-M.jpg','open_library','curated_red_white_royal_blue'),
('curated_heartstopper_volume_one','Heartstopper: Volume One','Alice Oseman','["Narrativa contemporánea"]','2018','es','https://covers.openlibrary.org/b/title/Heartstopper%3A%20Volume%20One-M.jpg','open_library','curated_heartstopper_volume_one'),
('curated_giovanni_s_room','Giovanni’s Room','James Baldwin','["Narrativa contemporánea"]','1956','es','https://covers.openlibrary.org/b/title/Giovanni%E2%80%99s%20Room-M.jpg','open_library','curated_giovanni_s_room'),
('curated_orlando','Orlando','Virginia Woolf','["Narrativa contemporánea"]','1928','es','https://covers.openlibrary.org/b/title/Orlando-M.jpg','open_library','curated_orlando'),
('curated_fun_home','Fun Home','Alison Bechdel','["Narrativa contemporánea"]','2006','es','https://covers.openlibrary.org/b/title/Fun%20Home-M.jpg','open_library','curated_fun_home'),
('curated_las_malas','Las malas','Camila Sosa Villada','["Narrativa contemporánea"]','2019','es','https://covers.openlibrary.org/b/title/Las%20malas-M.jpg','open_library','curated_las_malas'),
('curated_detransition_baby','Detransition, Baby','Torrey Peters','["Narrativa contemporánea"]','2021','es','https://covers.openlibrary.org/b/title/Detransition%2C%20Baby-M.jpg','open_library','curated_detransition_baby'),
('curated_middlesex','Middlesex','Jeffrey Eugenides','["Narrativa contemporánea"]','2002','es','https://covers.openlibrary.org/b/title/Middlesex-M.jpg','open_library','curated_middlesex'),
('curated_stone_butch_blues','Stone Butch Blues','Leslie Feinberg','["Narrativa contemporánea"]','1993','es','https://covers.openlibrary.org/b/title/Stone%20Butch%20Blues-M.jpg','open_library','curated_stone_butch_blues'),
('curated_el_beso_de_la_mujer_arana','El beso de la mujer araña','Manuel Puig','["Narrativa contemporánea"]','1976','es','https://covers.openlibrary.org/b/title/El%20beso%20de%20la%20mujer%20ara%C3%B1a-M.jpg','open_library','curated_el_beso_de_la_mujer_arana'),
('curated_el_vampiro_de_la_colonia_roma','El vampiro de la colonia Roma','Luis Zapata','["Narrativa contemporánea"]','1979','es','https://covers.openlibrary.org/b/title/El%20vampiro%20de%20la%20colonia%20Roma-M.jpg','open_library','curated_el_vampiro_de_la_colonia_roma'),
('curated_piranesi','Piranesi','Susanna Clarke','["Fantasía"]','2020','en','https://covers.openlibrary.org/b/title/Piranesi-M.jpg','open_library','curated_piranesi'),
('curated_circe','Circe','Madeline Miller','["Fantasía"]','2018','en','https://covers.openlibrary.org/b/title/Circe-M.jpg','open_library','curated_circe'),
('curated_the_invisible_life_of_addie_larue','The Invisible Life of Addie LaRue','V. E. Schwab','["Fantasía"]','2020','en','https://covers.openlibrary.org/b/title/The%20Invisible%20Life%20of%20Addie%20LaRue-M.jpg','open_library','curated_the_invisible_life_of_addie_larue'),
('curated_the_night_circus','The Night Circus','Erin Morgenstern','["Fantasía"]','2011','en','https://covers.openlibrary.org/b/title/The%20Night%20Circus-M.jpg','open_library','curated_the_night_circus'),
('curated_uprooted','Uprooted','Naomi Novik','["Fantasía"]','2015','en','https://covers.openlibrary.org/b/title/Uprooted-M.jpg','open_library','curated_uprooted'),
('curated_spinning_silver','Spinning Silver','Naomi Novik','["Fantasía"]','2018','en','https://covers.openlibrary.org/b/title/Spinning%20Silver-M.jpg','open_library','curated_spinning_silver'),
('curated_jonathan_strange_mr_norrell','Jonathan Strange & Mr Norrell','Susanna Clarke','["Fantasía"]','2004','en','https://covers.openlibrary.org/b/title/Jonathan%20Strange%20%26%20Mr%20Norrell-M.jpg','open_library','curated_jonathan_strange_mr_norrell'),
('curated_the_ocean_at_the_end_of_the_lane','The Ocean at the End of the Lane','Neil Gaiman','["Fantasía"]','2013','en','https://covers.openlibrary.org/b/title/The%20Ocean%20at%20the%20End%20of%20the%20Lane-M.jpg','open_library','curated_the_ocean_at_the_end_of_the_lane'),
('curated_good_omens','Good Omens','Neil Gaiman & Terry Pratchett','["Fantasía"]','1990','en','https://covers.openlibrary.org/b/title/Good%20Omens-M.jpg','open_library','curated_good_omens'),
('curated_the_house_in_the_cerulean_sea','The House in the Cerulean Sea','TJ Klune','["Fantasía"]','2020','en','https://covers.openlibrary.org/b/title/The%20House%20in%20the%20Cerulean%20Sea-M.jpg','open_library','curated_the_house_in_the_cerulean_sea'),
('curated_the_once_and_future_witches','The Once and Future Witches','Alix E. Harrow','["Fantasía"]','2020','en','https://covers.openlibrary.org/b/title/The%20Once%20and%20Future%20Witches-M.jpg','open_library','curated_the_once_and_future_witches'),
('curated_the_ten_thousand_doors_of_january','The Ten Thousand Doors of January','Alix E. Harrow','["Fantasía"]','2019','en','https://covers.openlibrary.org/b/title/The%20Ten%20Thousand%20Doors%20of%20January-M.jpg','open_library','curated_the_ten_thousand_doors_of_january'),
('curated_the_starless_sea','The Starless Sea','Erin Morgenstern','["Fantasía"]','2019','en','https://covers.openlibrary.org/b/title/The%20Starless%20Sea-M.jpg','open_library','curated_the_starless_sea'),
('curated_the_midnight_library','The Midnight Library','Matt Haig','["Fantasía"]','2020','en','https://covers.openlibrary.org/b/title/The%20Midnight%20Library-M.jpg','open_library','curated_the_midnight_library'),
('curated_the_buried_giant','The Buried Giant','Kazuo Ishiguro','["Fantasía"]','2015','en','https://covers.openlibrary.org/b/title/The%20Buried%20Giant-M.jpg','open_library','curated_the_buried_giant')
) as v(id,title,author,genre,year,language,cover,provider,source_id)
where not exists (select 1 from public.books existing where lower(trim(existing.title))=lower(trim(v.title)) and lower(trim(existing.author))=lower(trim(v.author)));
insert into public.reader_collection_books (collection_id,book_id,sort_order)
select c.id,b.id,10+row_number() over (partition by c.id order by b.title)
from public.reader_collections c cross join public.books b
where c.title='Dark academia: secretos y obsesiones' and ((lower(trim(b.title))='the secret history' and lower(trim(b.author))='donna tartt') or (lower(trim(b.title))='if we were villains' and lower(trim(b.author))='m. l. rio') or (lower(trim(b.title))='babel' and lower(trim(b.author))='r. f. kuang') or (lower(trim(b.title))='the maidens' and lower(trim(b.author))='alex michaelides') or (lower(trim(b.title))='the likeness' and lower(trim(b.author))='tana french') or (lower(trim(b.title))='the goldfinch' and lower(trim(b.author))='donna tartt') or (lower(trim(b.title))='dead poets society' and lower(trim(b.author))='n. h. kleinbaum') or (lower(trim(b.title))='vita nostra' and lower(trim(b.author))='marina dyachenko') or (lower(trim(b.title))='ace of spades' and lower(trim(b.author))='faridah àbíké-íyímídé') or (lower(trim(b.title))='catherine house' and lower(trim(b.author))='elisabeth thomas') or (lower(trim(b.title))='the secret place' and lower(trim(b.author))='tana french') or (lower(trim(b.title))='the lake of dead languages' and lower(trim(b.author))='carol goodman') or (lower(trim(b.title))='the cloisters' and lower(trim(b.author))='katy hays') or (lower(trim(b.title))='an education in malice' and lower(trim(b.author))='mira grant') or (lower(trim(b.title))='the atlas six' and lower(trim(b.author))='olivie blake'))
and not exists (select 1 from public.reader_collection_books cb where cb.collection_id=c.id and cb.book_id=b.id);
insert into public.reader_collection_books (collection_id,book_id,sort_order)
select c.id,b.id,10+row_number() over (partition by c.id order by b.title)
from public.reader_collections c cross join public.books b
where c.title='Lecturas LGTBIQ+ imprescindibles' and ((lower(trim(b.title))='la mala costumbre' and lower(trim(b.author))='alana s. portero') or (lower(trim(b.title))='call me by your name' and lower(trim(b.author))='andré aciman') or (lower(trim(b.title))='aristotle and dante discover the secrets of the universe' and lower(trim(b.author))='benjamin alire sáenz') or (lower(trim(b.title))='the song of achilles' and lower(trim(b.author))='madeline miller') or (lower(trim(b.title))='red, white & royal blue' and lower(trim(b.author))='casey mcquiston') or (lower(trim(b.title))='heartstopper: volume one' and lower(trim(b.author))='alice oseman') or (lower(trim(b.title))='giovanni’s room' and lower(trim(b.author))='james baldwin') or (lower(trim(b.title))='orlando' and lower(trim(b.author))='virginia woolf') or (lower(trim(b.title))='fun home' and lower(trim(b.author))='alison bechdel') or (lower(trim(b.title))='las malas' and lower(trim(b.author))='camila sosa villada') or (lower(trim(b.title))='detransition, baby' and lower(trim(b.author))='torrey peters') or (lower(trim(b.title))='middlesex' and lower(trim(b.author))='jeffrey eugenides') or (lower(trim(b.title))='stone butch blues' and lower(trim(b.author))='leslie feinberg') or (lower(trim(b.title))='el beso de la mujer araña' and lower(trim(b.author))='manuel puig') or (lower(trim(b.title))='el vampiro de la colonia roma' and lower(trim(b.author))='luis zapata'))
and not exists (select 1 from public.reader_collection_books cb where cb.collection_id=c.id and cb.book_id=b.id);
insert into public.reader_collection_books (collection_id,book_id,sort_order)
select c.id,b.id,10+row_number() over (partition by c.id order by b.title)
from public.reader_collections c cross join public.books b
where c.title='Fantasía independiente para perderse' and ((lower(trim(b.title))='piranesi' and lower(trim(b.author))='susanna clarke') or (lower(trim(b.title))='circe' and lower(trim(b.author))='madeline miller') or (lower(trim(b.title))='the invisible life of addie larue' and lower(trim(b.author))='v. e. schwab') or (lower(trim(b.title))='the night circus' and lower(trim(b.author))='erin morgenstern') or (lower(trim(b.title))='uprooted' and lower(trim(b.author))='naomi novik') or (lower(trim(b.title))='spinning silver' and lower(trim(b.author))='naomi novik') or (lower(trim(b.title))='jonathan strange & mr norrell' and lower(trim(b.author))='susanna clarke') or (lower(trim(b.title))='the ocean at the end of the lane' and lower(trim(b.author))='neil gaiman') or (lower(trim(b.title))='good omens' and lower(trim(b.author))='neil gaiman & terry pratchett') or (lower(trim(b.title))='the house in the cerulean sea' and lower(trim(b.author))='tj klune') or (lower(trim(b.title))='the once and future witches' and lower(trim(b.author))='alix e. harrow') or (lower(trim(b.title))='the ten thousand doors of january' and lower(trim(b.author))='alix e. harrow') or (lower(trim(b.title))='the starless sea' and lower(trim(b.author))='erin morgenstern') or (lower(trim(b.title))='the midnight library' and lower(trim(b.author))='matt haig') or (lower(trim(b.title))='the buried giant' and lower(trim(b.author))='kazuo ishiguro'))
and not exists (select 1 from public.reader_collection_books cb where cb.collection_id=c.id and cb.book_id=b.id);

