-- Librélula - esquema base Supabase
-- Ejecutar en Supabase SQL Editor con una cuenta propietaria del proyecto.
-- No usa service_role en el frontend. No borra tablas ni datos existentes.

create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  legacy_id bigint generated by default as identity unique,
  username text,
  avatar text default 'images/avatar/avatar1.png',
  bio text default '',
  profile_visual_settings jsonb not null default '{}'::jsonb,
  is_admin boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.books (
  id bigint generated by default as identity primary key,
  title text not null,
  author text not null,
  synopsis text default '',
  cover text default '',
  genre text default '',
  year integer,
  pages integer,
  publisher text default '',
  language text default 'es',
  isbn text default '',
  saga_name text default '',
  saga_number numeric,
  saga_key text default '',
  hero_color text default '',
  pdf_file text default '',
  epub_file text default '',
  provider text default '',
  provider_label text default '',
  source_id text default '',
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists books_title_idx on public.books using btree (title);
create index if not exists books_author_idx on public.books using btree (author);
create unique index if not exists books_isbn_unique_idx on public.books (isbn) where isbn is not null and isbn <> '';
alter table public.books add column if not exists provider text;
alter table public.books add column if not exists source_id text;

create unique index if not exists books_external_source_unique_idx on public.books (provider, source_id) where provider is not null and provider <> '' and source_id is not null and source_id <> '';

create table if not exists public.book_taxonomy (
  id bigint generated by default as identity primary key,
  book_id text not null references public.books(id) on delete cascade,
  kind text not null check (kind in ('theme', 'aesthetic', 'audience')),
  value text not null,
  position integer not null default 0,
  created_at timestamptz not null default now(),
  unique (book_id, kind, value)
);

create index if not exists book_taxonomy_book_idx on public.book_taxonomy (book_id, kind, position);

create table if not exists public.user_books (
  id bigint generated by default as identity primary key,
  legacy_user_id bigint not null references public.profiles(legacy_id) on delete cascade,
  book_id text not null references public.books(id) on delete cascade,
  status text not null default 'planned' check (status in ('planned', 'reading', 'paused', 'completed', 'dropped', 'rereading')),
  progress integer not null default 0 check (progress >= 0 and progress <= 100),
  score numeric,
  notes text,
  started_at date,
  finished_at date,
  read_count integer not null default 0,
  paused_at date,
  dropped_at date,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (legacy_user_id, book_id)
);

create index if not exists user_books_user_idx on public.user_books (legacy_user_id, status);
create index if not exists user_books_book_idx on public.user_books (book_id);

create table if not exists public.book_reviews (
  id bigint generated by default as identity primary key,
  legacy_user_id bigint not null references public.profiles(legacy_id) on delete cascade,
  book_id text not null references public.books(id) on delete cascade,
  rating numeric,
  title text default '',
  review text default '',
  contains_spoilers boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (legacy_user_id, book_id)
);

create index if not exists book_reviews_book_idx on public.book_reviews (book_id, created_at desc);

create table if not exists public.book_review_vibes (
  id bigint generated by default as identity primary key,
  review_id bigint not null references public.book_reviews(id) on delete cascade,
  vibe text not null,
  created_at timestamptz not null default now(),
  unique (review_id, vibe)
);

create table if not exists public.book_postits (
  id bigint generated by default as identity primary key,
  legacy_user_id bigint not null references public.profiles(legacy_id) on delete cascade,
  book_id text not null references public.books(id) on delete cascade,
  quote text not null,
  page integer,
  color text not null default 'yellow',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists book_postits_user_book_idx on public.book_postits (legacy_user_id, book_id, created_at desc);

create table if not exists public.profile_favorite_books (
  id bigint generated by default as identity primary key,
  legacy_user_id bigint not null references public.profiles(legacy_id) on delete cascade,
  book_id text not null references public.books(id) on delete cascade,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  unique (legacy_user_id, book_id)
);

create table if not exists public.profile_favorite_authors (
  id bigint generated by default as identity primary key,
  legacy_user_id bigint not null references public.profiles(legacy_id) on delete cascade,
  author_name text not null,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  unique (legacy_user_id, author_name)
);

create or replace function public.touch_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

do $$
begin
  if not exists (select 1 from pg_trigger where tgname = 'profiles_touch_updated_at') then
    create trigger profiles_touch_updated_at before update on public.profiles
    for each row execute function public.touch_updated_at();
  end if;

  if not exists (select 1 from pg_trigger where tgname = 'books_touch_updated_at') then
    create trigger books_touch_updated_at before update on public.books
    for each row execute function public.touch_updated_at();
  end if;

  if not exists (select 1 from pg_trigger where tgname = 'user_books_touch_updated_at') then
    create trigger user_books_touch_updated_at before update on public.user_books
    for each row execute function public.touch_updated_at();
  end if;

  if not exists (select 1 from pg_trigger where tgname = 'book_reviews_touch_updated_at') then
    create trigger book_reviews_touch_updated_at before update on public.book_reviews
    for each row execute function public.touch_updated_at();
  end if;

  if not exists (select 1 from pg_trigger where tgname = 'book_postits_touch_updated_at') then
    create trigger book_postits_touch_updated_at before update on public.book_postits
    for each row execute function public.touch_updated_at();
  end if;
end $$;

create or replace function public.current_legacy_user_id()
returns bigint
language sql
stable
security definer
set search_path = public
as $$
  select legacy_id from public.profiles where id = auth.uid()
$$;

create or replace function public.current_user_is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select coalesce(is_admin, false) from public.profiles where id = auth.uid()
$$;

alter table public.profiles enable row level security;
alter table public.books enable row level security;
alter table public.book_taxonomy enable row level security;
alter table public.user_books enable row level security;
alter table public.book_reviews enable row level security;
alter table public.book_review_vibes enable row level security;
alter table public.book_postits enable row level security;
alter table public.profile_favorite_books enable row level security;
alter table public.profile_favorite_authors enable row level security;

do $$
begin
  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'profiles' and policyname = 'profiles_select_authenticated') then
    create policy profiles_select_authenticated on public.profiles for select to authenticated using (true);
  end if;
  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'profiles' and policyname = 'profiles_insert_own') then
    create policy profiles_insert_own on public.profiles for insert to authenticated with check (id = auth.uid());
  end if;
  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'profiles' and policyname = 'profiles_update_own') then
    create policy profiles_update_own on public.profiles for update to authenticated using (id = auth.uid()) with check (id = auth.uid());
  end if;

  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'books' and policyname = 'books_select_all') then
    create policy books_select_all on public.books for select to anon, authenticated using (true);
  end if;
  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'books' and policyname = 'books_insert_admin') then
    create policy books_insert_admin on public.books for insert to authenticated with check (public.current_user_is_admin());
  end if;
  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'books' and policyname = 'books_update_admin') then
    create policy books_update_admin on public.books for update to authenticated using (public.current_user_is_admin()) with check (public.current_user_is_admin());
  end if;
  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'books' and policyname = 'books_delete_admin') then
    create policy books_delete_admin on public.books for delete to authenticated using (public.current_user_is_admin());
  end if;

  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'book_taxonomy' and policyname = 'book_taxonomy_select_all') then
    create policy book_taxonomy_select_all on public.book_taxonomy for select to anon, authenticated using (true);
  end if;
  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'book_taxonomy' and policyname = 'book_taxonomy_write_admin') then
    create policy book_taxonomy_write_admin on public.book_taxonomy for all to authenticated using (public.current_user_is_admin()) with check (public.current_user_is_admin());
  end if;

  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'user_books' and policyname = 'user_books_select_own') then
    create policy user_books_select_own on public.user_books for select to authenticated using (legacy_user_id = public.current_legacy_user_id());
  end if;
  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'user_books' and policyname = 'user_books_insert_own') then
    create policy user_books_insert_own on public.user_books for insert to authenticated with check (legacy_user_id = public.current_legacy_user_id());
  end if;
  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'user_books' and policyname = 'user_books_update_own') then
    create policy user_books_update_own on public.user_books for update to authenticated using (legacy_user_id = public.current_legacy_user_id()) with check (legacy_user_id = public.current_legacy_user_id());
  end if;
  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'user_books' and policyname = 'user_books_delete_own') then
    create policy user_books_delete_own on public.user_books for delete to authenticated using (legacy_user_id = public.current_legacy_user_id());
  end if;

  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'book_reviews' and policyname = 'book_reviews_select_all') then
    create policy book_reviews_select_all on public.book_reviews for select to anon, authenticated using (true);
  end if;
  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'book_reviews' and policyname = 'book_reviews_insert_own') then
    create policy book_reviews_insert_own on public.book_reviews for insert to authenticated with check (legacy_user_id = public.current_legacy_user_id());
  end if;
  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'book_reviews' and policyname = 'book_reviews_update_own') then
    create policy book_reviews_update_own on public.book_reviews for update to authenticated using (legacy_user_id = public.current_legacy_user_id()) with check (legacy_user_id = public.current_legacy_user_id());
  end if;
  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'book_reviews' and policyname = 'book_reviews_delete_own') then
    create policy book_reviews_delete_own on public.book_reviews for delete to authenticated using (legacy_user_id = public.current_legacy_user_id());
  end if;

  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'book_review_vibes' and policyname = 'book_review_vibes_select_all') then
    create policy book_review_vibes_select_all on public.book_review_vibes for select to anon, authenticated using (true);
  end if;
  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'book_review_vibes' and policyname = 'book_review_vibes_write_owner') then
    create policy book_review_vibes_write_owner on public.book_review_vibes for all to authenticated
    using (exists (select 1 from public.book_reviews r where r.id = review_id and r.legacy_user_id = public.current_legacy_user_id()))
    with check (exists (select 1 from public.book_reviews r where r.id = review_id and r.legacy_user_id = public.current_legacy_user_id()));
  end if;

  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'book_postits' and policyname = 'book_postits_select_own') then
    create policy book_postits_select_own on public.book_postits for select to authenticated using (legacy_user_id = public.current_legacy_user_id());
  end if;
  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'book_postits' and policyname = 'book_postits_write_own') then
    create policy book_postits_write_own on public.book_postits for all to authenticated using (legacy_user_id = public.current_legacy_user_id()) with check (legacy_user_id = public.current_legacy_user_id());
  end if;

  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'profile_favorite_books' and policyname = 'profile_favorite_books_select_own') then
    create policy profile_favorite_books_select_own on public.profile_favorite_books for select to authenticated using (legacy_user_id = public.current_legacy_user_id());
  end if;
  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'profile_favorite_books' and policyname = 'profile_favorite_books_write_own') then
    create policy profile_favorite_books_write_own on public.profile_favorite_books for all to authenticated using (legacy_user_id = public.current_legacy_user_id()) with check (legacy_user_id = public.current_legacy_user_id());
  end if;

  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'profile_favorite_authors' and policyname = 'profile_favorite_authors_select_own') then
    create policy profile_favorite_authors_select_own on public.profile_favorite_authors for select to authenticated using (legacy_user_id = public.current_legacy_user_id());
  end if;
  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'profile_favorite_authors' and policyname = 'profile_favorite_authors_write_own') then
    create policy profile_favorite_authors_write_own on public.profile_favorite_authors for all to authenticated using (legacy_user_id = public.current_legacy_user_id()) with check (legacy_user_id = public.current_legacy_user_id());
  end if;
end $$;
